export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
export const GET_ALL_ORDERD_PRODUCTS="GET_ALL_ORDERD_PRODUCTS";
export const GET_SINGLE_USER_ORDERD_PRODUCTS="GET_SINGLE_USER_ORDERD_PRODUCTS";
export const UPDATE_ORDER_STATUS="UPDATE_ORDER_STATUS";
export const USER_SPECIFIC_ORDERS="USER_SPECIFIC_ORDERS";
